### ISSUE TITLE
Ordering of action

### ISSUE THREAD

**Issue by okohll** [616slayer616/gradle-minify-plugin#14]
Hi,

This may be more of a question about Gradle configuration, I'm not sure, but I can't find the answer in the Gradle docs.

How do you specify _when_ the minification should run?

I have a number of custom tasks (e.g. to combine many JS files into one) which I want to run after minification but they're currently running before.
I've tried specifying them as

`task combineJs(dependsOn: minify) { ... }`

and

```
task combineJs() {
  mustRunAfter "minify"
  ...
}
```

but neither work.

Many thanks for releasing this plugin, it's great.

**Comment by 616slayer616** [comment]
Hi
thank you for using the plugin.
Your question is a gradle question but I will try to help you.

In my project the setup is reversed: I have a "buildStatic" task that updates the js and css files and then the minify ist called.
I do this with 
`buildStatic.finalizedBy minify`.

Maybe you could try that reversed.

I'm always having problems with ordering when adding tasks one might be missing "doLast" section.

Maybe this on stackoverflow helps you:
https://stackoverflow.com/questions/19682011/gradle-dependson-ordering

This is an interesting statement from there:
"dependsOn doesn't fix any order for the tasks"

**Comment by okohll** [comment]
Thanks for the quick reply - it was a doLast that I was missing.
