### ISSUE TITLE
Add "source map url" comment line.

### ISSUE THREAD

**Issue by raccoon1515** [616slayer616/gradle-minify-plugin#23]
Minified files should have a comment-line like "`# sourceMappingURL=index.min.js.map`" at the end of the file, to allow browser devtools parse sourcemap automaticly.

**Comment by 616slayer616** [comment]
That would be a feature of the minifier itself so you would have to request the feature from [Google Closure Compiler](https://github.com/google/closure-compiler).

**Comment by izeye** [comment]
@raccoon1515 For your information, the support has been added in `org.padler.gradle.minify` 1.6.0.

See https://github.com/616slayer616/gradle-minify-plugin/releases/tag/v1.6.0

**Comment by raccoon1515** [comment]
That's great! Thx!
