### ISSUE TITLE
Add file filtartion in srcDirectory

### ISSUE THREAD

**Issue by raccoon1515** [616slayer616/gradle-minify-plugin#24]
Now `jsDstDir` and `cssDstDir` are not filtering files. Plugin tries to minify all files in derectory and fails if there are not suitable file. `jsDstDir` should filter and minify only *.js files, as for `cssDstDir`.

**Comment by 616slayer616** [comment]
The minifier should not fail when encountering non js or css files.
What type of file created the problem and which version are you using?

For more safety I could resolve this like this:
https://github.com/616slayer616/gradle-minify-plugin/pull/26

**Comment by raccoon1515** [comment]
Yes, this amazing!
