### ISSUE TITLE
Compile with jdk8

### ISSUE THREAD

**Issue by rnentjes** [616slayer616/gradle-minify-plugin#28]
Because of reasons we still build with jdk 8, is it possible to release a version that is compatible with jdk 8? 

At the moment I get the following error:

```
java.lang.UnsupportedClassVersionError: org/padler/gradle/minify/MinifyPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/padler/gradle/minify/MinifyPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by 616slayer616** [comment]
Interesting.
There might be a very simple fix could you try it with [this 1.5.1-SNAPSHOT snapshot](https://github.com/616slayer616/gradle-minify-plugin/tree/java_8_compatibility)?

**Comment by rnentjes** [comment]
Yes, that helps. Amazing response time btw., thank you!

**Comment by 616slayer616** [comment]
happy to help!

I will create a release
