### ISSUE TITLE
Supporting multiple source directories

### ISSUE THREAD

**Issue by xtianus** [616slayer616/gradle-minify-plugin#34]
I'm not sure how to specify more than one source folder.
If I use a collection I get this error:

`Directory 'C:\work\...\file collection' specified for property 'jsSrcDir' does not exist.
`

where the collection is

`jsSrcDir = project.files(fileTree("${rootDir}/src/main/webapp/res/js"), fileTree("${rootDir}/src/main/webapp/res/engine"))
`

**Comment by 616slayer616** [comment]
Multiple source directories are not supported (yet).

One solution would be this issue [https://github.com/616slayer616/gradle-minify-plugin/issues/12](https://github.com/616slayer616/gradle-minify-plugin/issues/12) but there hasn't been any work done and I don't know how to implement this.

Allowing multiple source directories by specifying an array would be possible but what should the target directory be?
It would all be put into the same target directory and then there could be naming conflicts.

**Comment by xtianus** [comment]
Maybe we could have two options for the output folder: either write to the same folder of the source file (with a .min extension) or write everything to a single output folder. You shouldn't worry about naming conflicts and just overwrite what's there. It's up to the developer to use different names for different source files.

In the meantime I had a look at the eriwen plugin. It seems to be fairly complete. Can I suggest that you copy some of the code from there? You might be the one to inherit that project. Many people would be immensely grateful.

**Comment by 616slayer616** [comment]
We have now re-release the plugin here: https://github.com/gradle-webtools/gradle-minify-plugin.
Now it's possible to configure multiple tasks with different directories.
The README has an example.

It would be great if you could look into it and check whether this is what you need.
