### ISSUE TITLE
Feature request gradle incremental builds

### ISSUE THREAD

**Issue by timon-schelling** [616slayer616/gradle-minify-plugin#8]
I think this gradle plugin is already awesome and easy to use.

But it would be great if it sported gradle incremental builds to make builds faster.
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

Currently I use this configuration to implement them my self.
```kotlin
val minify by tasks
minify.apply {
    inputs.dir("$buildDir/minify/src/js") // here you could use jsSrcDir from configuration
    inputs.dir("$buildDir/minify/src/css") // here you could use cssSrcDir from configuration
    outputs.dir("$buildDir/minify/dst/js") // here you could use jsDstDir from configuration
    outputs.dir("$buildDir/minify/dst/css") // here you could use cssDstDir from configuration
}
```
or in a more project independent way
```kotlin
val minify by tasks
minify.apply {
    inputs.dir(jsSrcDir)
    inputs.dir(cssSrcDir)
    outputs.dir(jsDstDir)
    outputs.dir(cssDstDir)
}
```

The configuration could then look like this.
```kotlin
minification {
    jsSrcDir = "$buildDir/minify/src/js"
    jsDstDir = "$buildDir/minify/dst/js"
    cssSrcDir = "$buildDir/minify/src/css"
    cssDstDir = "$buildDir/minify/dst/css"

    incrementalBuilds = true // default should be true
}
```

**Comment by timon-schelling** [comment]
I think this configuration makes my point clearer.

```kotlin
val minify by tasks
minify.apply {
    inputs.dir(minification.jsSrcDir)
    inputs.dir(minification.cssSrcDir)
    outputs.dir(minification.jsDstDir)
    outputs.dir(minification.cssDstDir)
}
```

**Comment by 616slayer616** [comment]
I would like that to speed up builds and skip up to date tasks.
Unfortunately I have no idea how to achieve this.

The gradle plugin creation documentation is not very exhaustive in my opinion.

I will see if I can find more information.

Do you have experience creating a task with input and output data?

**Comment by timon-schelling** [comment]
I have some experience but not on the plugin site of things. 
I only know how to implement in my kotlin gradle config script. 
As you can see in my comment.
https://github.com/616slayer616/gradle-minify-plugin/issues/8#issuecomment-608501615 

I think this resource might help. 
https://docs.gradle.org/current/userguide/custom_tasks.html#incremental_tasks
There using kotlin so some annotation names might differ.

**Comment by timon-schelling** [comment]
Pull request is created

**Comment by 616slayer616** [comment]
It is released with 1.4.0-SNAPSHOT. 

My configuration looks like this:

```
minification {
    cssDstDir = "$buildDir/$distDir/css"
    cssSrcDir = "$rootDir/src/main/resources/static/css"
    jsDstDir = "$buildDir/$distDir/js"
    jsSrcDir = "$rootDir/src/main/resources/static/js"
}
```

But I don't get the UP-TO-DATE message on repeated executions.

**Comment by timon-schelling** [comment]
```kotlin
plugins {
    id("org.padler.gradle.minify") version "1.4.0-SNAPSHOT"
}

minification {
    jsSrcDir = "$buildDir/minify/src/js"
    jsDstDir = "$buildDir/minify/dst/js"
    cssSrcDir = "$buildDir/minify/src/css"
    cssDstDir = "$buildDir/minify/dst/css"
}

val minify by tasks
minify.apply {
    group = "build"
}
```
I use this configuration and it works perfectly.

**Comment by timon-schelling** [comment]
btw why do you add minify to `build setup` group and not to `build`?

**Comment by 616slayer616** [comment]
That musst be it:
`val minify by tasks`
What dies that do?
I will try this out tomorrow.


To the prepare build: I don't know it doesn't really fit.
Maybe I got it from the example.
Build isn't perfect either but it's better.
I will include this.

**Comment by timon-schelling** [comment]
im using kotlin as gradle build language (instead of grovy) kotlin is type safe that couches that ```val minify by tasks``` val declaration. if you use grovy you can just use: 
```
plugins {
    id "org.padler.gradle.minify"  version "1.4.0-SNAPSHOT"
}

minification {
    jsSrcDir = "$buildDir/minify/src/js"
    jsDstDir = "$buildDir/minify/dst/js"
    cssSrcDir = "$buildDir/minify/src/css"
    cssDstDir = "$buildDir/minify/dst/css"
}

tasks.minify {
    group = "build"
}
```

**Comment by 616slayer616** [comment]
Ah ok.

But this 
```
tasks.minify {
    group = "build"
}
```
Only changes the group to build?
So I shouldn't have problems with the UP-TO-DATE stuff.

**Comment by timon-schelling** [comment]
Yes

**Comment by timon-schelling** [comment]
Should this be closed?

**Comment by 616slayer616** [comment]
I think so, although I did not get it to work yet.

**Comment by 616slayer616** [comment]
I know what the problem was now.
I have another task that copies the files to the destination. Then it calls the minify task.
When I change that to only minify I get the UP-TO-DATE on the second run.

Thank you for the improvement.
